Hw1 2 3
PetrovAlexey/android_abbyy pull request #9
Opened 2020-03-10 06:35 UTC by PetrovAlexey

Не получается сделать базу данных, в нее не загружаются данные при первой инициализации

2020-05-09 10:51 UTC, IvanShafran requested changes

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/App.kt
> +        val notes = noteRepository.getNotes()
Получение заметок надо в сервисе делать. Тут main thread тормозиться. А IntentService обрабатывает всё на фоновом потоке по умолчанию

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/BackupIntentService.kt
> +                fos?.close()
В Kotlin есть аналог try with resources:
try {
   openFileOutpur(...).use { fos ->
      // Code here
   }
} catch () {
}
https://kotlinlang.org/docs/tutorials/kotlin-for-py/scoped-resource-usage.html

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +
Многовато отступов

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +    private var cameraView: CameraView? = null
Kotlin extensions подключены, поэтому можно не заводить переменные, а сразу использовать View

https://medium.com/nuances-of-programming/kotlin-android-extensions-полное-руководство-42ad43b029d7

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +        while(!result.isComplete){
Не, так не пойдёт. 
1. Перенеси весь код ниже в OnSuccessListener
2. Создание записи в БД надо в фоновом потоке делать. Используй корутины

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +            Date(1576174880000),
Почему тут хардкод?

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        if (App.noteRepository.getNotes().isEmpty()) {
Этот if уже можно удалить

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/MainFragment.kt
> +                if (resources.getBoolean(R.bool.is_phone)) {
Этот код повторяет работу Activity.
Можно вызвать тот метод:
- (requireActivity() as MainActivity).openNote(id)
- в Activity commit на commitAllowingStateLoss поставить

2020-05-09 10:51 UTC, IvanShafran commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/NoteAdapter.kt
> +                                App.noteRepository.deleteNote(note.id)
Надо в фоне делать. Используй корутины

2020-05-10 12:06 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/App.kt
> +        val notes = noteRepository.getNotes()
done.

2020-05-10 12:06 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/BackupIntentService.kt
> +                fos?.close()
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +    private var cameraView: CameraView? = null
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +        while(!result.isComplete){
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/CameraActivity.kt
> +            Date(1576174880000),
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/MainActivity.kt
> +        if (App.noteRepository.getNotes().isEmpty()) {
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/MainFragment.kt
> +                if (resources.getBoolean(R.bool.is_phone)) {
done.

2020-05-10 12:07 UTC, PetrovAlexey commented on MyApplicationFragment[HW1_2]/app/src/main/java/com/example/myapplication/NoteAdapter.kt
> +                                App.noteRepository.deleteNote(note.id)
done.

2020-05-10 12:20 UTC, IvanShafran approved these changes

2020-05-12 04:32 UTC, merged